src/jobs/urls.py
from django.conf.urls import url

from .views import (JobIndex, JobAdd, JobDetails, JobOutput, JobConfiguration1,
                    JobConfiguration2, JobOverview, JobPreprocessing, JobSetup,
                    JobAddFromURL)

urlpatterns = [
    url(r'^$', JobIndex.as_view(), name='index'),
    url(r'^add$', JobAdd.as_view(), name='add'),
    url(r'^setup$', JobSetup.as_view(), name='setup'),
    url(r'^url$', JobAddFromURL.as_view(), name='add_from_url'),
    url(r'^(?P<pk>[0-9\w-]+)/detail$', JobDetails.as_view(), name='details'),
    url(r'^(?P<pk>[0-9\w-]+)/preprocessing$', JobPreprocessing.as_view(), name='preprocessing'),
    url(r'^(?P<pk>[0-9\w-]+)/configure_1$', JobConfiguration1.as_view(), name='configure1'),
    url(r'^(?P<pk>[0-9\w-]+)/configure_2$', JobConfiguration2.as_view(), name='configure2'),
    url(r'^(?P<pk>[0-9\w-]+)/overview$', JobOverview.as_view(), name='overview'),
    url(r'^(?P<pk>[0-9\w-]+)/output.json$', JobOutput.as_view(), name='output'),
]

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('jobs.urls', namespace='jobs')),
    url(r'^admin/', admin.site.urls),
    url(r'^admin/rq', include('django_rq.urls')),
]

src/jobs/models.py
import cPickle as pickle
import glob
import os
import subprocess
import uuid

from django.conf import settings
from django.core.cache import cache
from django.core.urlresolvers import reverse
from django.core.validators import MaxValueValidator
from django.db import models
from django.db import transaction

from django_rq import job

from core.fields import ContentTypeRestrictedFileField


def job_directory_path(instance, filename):
    """ Function to generate the correct upload path folder
        Every job should have its own folder
        <upload_dir>/<hex-id-of-job>/<filename>
    """
    return os.path.join(settings.JOB_FILES_UPLOAD_DIR,
                        instance.id.hex,
                        'inputs',
                        filename)


@job
def run_setup(job_instance):
    """ Function to run the setup tools on HemeLB scripts to convert the profile file
        and geometry file in form of .stl and .pr2 into the input for the job execution
        which are .xml and .gmy
    """
    command = "/var/src/hemelb/virtualenv/bin/python \
    /var/src/hemelb/Tools/setuptool/scripts/hemelb-setup-nogui \
    --stl {} {} ".format(job_instance.stl_file.name, job_instance.profile_file.name)

    completed = subprocess.call(command, shell=True)

    if completed == 0:
        # Assign generated .gmy and .xml to the correct fields
        job_instance.configuration_file.name = job_instance.stl_file.name.replace('.stl', '.xml')
        job_instance.input_file.name = job_instance.stl_file.name.replace('.stl', '.gmy')
        job_instance.status = job_instance.ADDED
    else:
        job_instance.status = job_instance.FAILED

    job_instance.save()


@job
def run_job(job_instance):
        """ Function to be called in the background to run the submitted job
            This function will compose the correct command for the job
            and make sure that the stdout and stderr of the command is correctly
            piped into the correct files
        """

        job_instance.run_hemelb()

        job_instance.run_post_processing()
        job_instance.package_output()

        job_instance.status = job_instance.DONE
        job_instance.save(update_fields=['status'])

        # Only upload job if it is successful, and queue it again so another
        # worker in lower priority can take over
        upload_job.delay(job_instance)


@job
def upload_job(job_instance):
    from core.utils import PersistentStorage
    storage = PersistentStorage()
    storage.save_job(job_instance)
    print "uploading {}".format(job_instance.id)


class Job(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    configuration_file = ContentTypeRestrictedFileField(upload_to=job_directory_path,
                                                        verbose_name="HemeLB config file (.xml)",
                                                        content_types=["text/xml"],
                                                        blank=True)
    input_file = ContentTypeRestrictedFileField(upload_to=job_directory_path,
                                                verbose_name="GMY geometry file (.gmy)",
                                                content_types=["application/octet-stream"],
                                                blank=True)

    stl_file = ContentTypeRestrictedFileField(upload_to=job_directory_path,
                                              verbose_name="STL geometry file (.stl)",
                                              content_types=["application/octet-stream"],
                                              blank=True)

    profile_file = ContentTypeRestrictedFileField(upload_to=job_directory_path,
                                                  verbose_name="Profile file (.pr2)",
                                                  content_types=["application/octet-stream"],
                                                  blank=True)

    output_file = models.FileField(upload_to=job_directory_path,
                                   blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    CONTAINER_CHOICES = (
        (1, 'seiryuz/hemelb-core:0.0.2'),
        (2, 'seiryuz/hemelb-core:0.0.3'),
    )
    container_image = models.IntegerField(choices=CONTAINER_CHOICES, default=1,
                                          verbose_name="HemeLB Version")

    INSTANCE_CHOICES = (
        (2, '2 Virtual Cores'),
        (4, '4 Virtual Cores'),
        (8, '8 Virtual Cores'),
        (16, '16 Virtual Cores'),
        (36, '36 Virtual Cores'),
    )
    instance_type = models.IntegerField(choices=INSTANCE_CHOICES, default=2,
                                        verbose_name="Machine Type")
    instance_count = models.IntegerField(default=1, validators=[MaxValueValidator(36)],
                                         verbose_name="How many machine")

    ADDED = 1
    QUEUED = 2
    RUNNING = 10
    DONE = 3
    PREPROCESSING = 4
    PREVIOUS = 5
    POSTPROCESSING = 6
    FAILED = 0
    STATUS_CHOICES = (
        (ADDED, 'Added'),
        (QUEUED, 'Queued'),
        (RUNNING, 'Running'),
        (POSTPROCESSING, 'Running postprocessing scripts'),
        (DONE, 'Done'),
        (FAILED, 'Failed'),
        (PREPROCESSING, 'Preprocessing'),
        (PREVIOUS, 'Previous Job on S3'),
    )
    status = models.IntegerField(choices=STATUS_CHOICES, default=ADDED)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.__repr__()

    def __repr__(self):
        return self.id.hex

    def get_absolute_url(self):
        return reverse('jobs:details', kwargs={"pk": str(self.id)})

    def get_next_step_url(self):
        if self.status == self.ADDED:
            return reverse('jobs:configure1', kwargs={"pk": str(self.id)})
        if self.status == self.PREPROCESSING:
            return reverse('jobs:preprocessing', kwargs={"pk": str(self.id)})
        else:
            return self.get_absolute_url()

    def get_job_directory_path(self):
        return os.path.join(settings.JOB_FILES_UPLOAD_DIR,
                            self.id.hex)

    def get_input_directory_path(self):
        return os.path.join(self.get_job_directory_path(),
                            'inputs')

    def get_log_directory_path(self):
        return os.path.join(self.get_job_directory_path(),
                            'logs')

    def get_metadata_path(self):
        return os.path.join(self.get_job_directory_path(),
                            'metadata')

    def get_result_directory_path(self):
        return os.path.join(self.get_job_directory_path(),
                            'result')

    def get_result_extracted_directory_path(self):
        return os.path.join(self.get_result_directory_path(),
                            'Extracted/*')

    def get_output_path(self):
        return os.path.join(self.get_result_directory_path(),
                            '{}.vtu'.format(str(self.id)))

    def get_packaged_output_path(self):
        return os.path.join(self.get_result_directory_path(),
                            '{}.tar.gz'.format(str(self.id)))

    def get_log_file_path(self, log_type):
        return os.path.join(self.get_log_directory_path(),
                            log_type)

    def get_container_image_url(self):
        container_string = self.get_container_image_display().split(':')[0]
        return "http://hub.docker.com/r/{}".format(container_string)

    def get_instance_id(self):
        if int(self.instance_type) == 2:
            return 'c4.large'
        elif int(self.instance_type) == 4:
            return 'c4.xlarge'
        elif int(self.instance_type) == 8:
            return 'c4.2xlarge'
        elif int(self.instance_type) == 16:
            return 'c4.4xlarge'
        elif int(self.instance_type) == 36:
            return 'c4.8xlarge'

    def get_total_virtual_core_count(self):
        return int(self.instance_count) * int(self.instance_type)

    def get_physical_core_count(self):
        # On AWS it is vCPU, 2 of them share the same 1 physical core
        return int(self.instance_type) / 2

    def get_output(self, log_type, force=False):
        key = "{}:log:{}".format(self.id.hex, log_type)

        # Hit the cache first
        output = cache.get(key)

        # Cache Miss
        if not output or force is True:

            # Read from the file, this is slow
            with open(self.get_log_file_path(log_type), 'r') as _file:
                output = _file.read()

            # Save it to the cache, depending on the likelihood of the content
            # being updated
            if self.status != self.DONE and self.status != self.FAILED:
                cache.set(key, output, timeout=5)
            else:
                cache.set(key, output, timeout=5000)

        return output

    def run_hemelb(self):
        command = "export ANSIBLE_HOST_KEY_CHECKING=False; \
        export AWS_SECRET_ACCESS_KEY={}; \
        export AWS_ACCESS_KEY_ID={}; \
        /var/www/hemeweb/virtualenv/bin/ansible-playbook \
        -u ubuntu \
        --extra-vars 'image={} master_ip={} worker_node_count={}  \
        instance_tags={} input={} output={} \
        worker_instance_type={} log_file={} physical_core_count={} container_image={}' \
        jobs/scripts/aws_ec2.yml\
        ".format(
            settings.AWS_SECRET_ACCESS_KEY,
            settings.AWS_ACCESS_KEY_ID,
            settings.HEMEWEB_IMAGE_ID,
            settings.HOST_IP,
            self.instance_count,
            "job-{}".format(self.id),
            self.configuration_file.name,
            self.get_result_directory_path(),
            self.get_instance_id(),
            self.get_log_file_path('hemelb'),
            self.get_physical_core_count(),
            self.get_container_image_display(),
        )

src/templates/jobs/add.html
{% extends "base.html" %}
{% load hemeweb_tags %}

{% block body %}

<h1>Add a new job</h1>

<form method="post" enctype="multipart/form-data">

  {% csrf_token %}

{% for field in form.visible_fields %}
  <div class="form-group">

    <label for="{{ field.name }}">{{ field.label_tag }}</label>
    {{ field|addcss:"form-control" }}
    <span style='color:red'>{{ field.errors.as_text }}</span>
  </div>
{% endfor %}

  <button> Submit </button>

</form>


{% endblock %}

src/templates/jobs/configure_1.html
{% extends "jobs/detail_base.html" %}

{% block body_class %} configure_job_1 {% endblock %}

{% block body_detail %}


<br />


<div class="row bottom-padding">
  <div class="col-lg-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title">Configure HemeLB execution</h2>
      </div>
      <div class="panel-body">
        <p>The panel below contains content from the HemeLB configuration file you provided. You can modify the content of the file and save it back before proceeding to the next step.</p>
        <div id="editor">{{ config_file }}</div>

        <br />

        <div class="row bottom-padding ">
          <div class="col-lg-2">
            <button class="btn btn-primary" id="save"> <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> Save (Ctrl+S)</button>
          </div>
          <div class="col-lg-2 col-lg-offset-8 right">
            <a href="{% url 'jobs:configure2' job.id %}"class="btn btn-default">Next step <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> </a>
              </div>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-2 col-lg-offset-5 center">
          <div class="alert alert-success hide-animate" role="alert"> <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> File saved</div>
      </div>
      </div>


    </div>
  </div>
</div>




{% endblock %}



{% block extra_javascript %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/mode-xml.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/theme-solarized_dark.js"></script>


<script type="text/javascript" charset="utf-8">
  // using jQuery
  function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie != '') {
          var cookies = document.cookie.split(';');
          for (var i = 0; i < cookies.length; i++) {
              var cookie = jQuery.trim(cookies[i]);
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) == (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
  }

  var csrftoken = getCookie('csrftoken'),
      objectId = "{{ job.id }}",
      editor = ace.edit("editor"),
      $alert = $('.alert'),
      alertTimeoutID;

  function showAlert() {
    clearTimeout(alertTimeoutID);

    $alert.removeClass('hide-animate');

    alertTimeoutID = setTimeout(function(){
        $alert.addClass("hide-animate");
    }, 1000);
  }


  var saveContent = function(){
      var data = {content: editor.getValue()};
      $.ajax({
        type: "POST",
        url: "/" + objectId + "/configure_1",
        data: data,
        success: function(data) {
          showAlert();
          //alert('HemeLB configuration saved');
          //editor.setValue(data.content);
        },
        error: function(request, status, error) {
          alert('Cannot save configuration. Please contact administrator');
        }
      });
  };

  // Configure editor
  editor.setTheme("ace/theme/solarized_dark");
  editor.getSession().setMode("ace/mode/xml");
  editor.getSession().setUseWrapMode(true);
  editor.commands.addCommand({
    name: 'save',
    bindKey: {win: 'Ctrl-s',  mac: 'Command-s'},
    exec: function(editor) {
        //...
        saveContent();
    },
  });

  // Configure ajax to send csrf token
  function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  $.ajaxSetup({
      beforeSend: function(xhr, settings) {
          if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken);
          }
      }
  });


  // Add listener to save button
  $(document).ready(function(){

      $('.configure_job_1').on('click', '#save', function(){
        saveContent();
      });

  });
</script>

{% endblock %}

src/templates/jobs/configure_2.html
{% extends "jobs/detail_base.html" %}
{% load hemeweb_tags %}

{% block body_class %} configure_job_2 {% endblock %}

{% block body_detail %}

<br />

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title">Configure HemeWeb job execution</h2>
      </div>
      <div class="panel-body">
        <p>Here, you can configure how the simulation will run. Configure the type of compute node and how many of it HemeWeb should start for the simulation. Also, specify the
        HemeLB container version to use. </p>
        <br />
      <form method="post" enctype="multipart/form-data">

      {% csrf_token %}

      {% for field in form.visible_fields %}
        <div class="form-group">

          <label for="{{ field.name }}">{{ field.label_tag }}</label>
          {{ field|addcss:"form-control" }}
          <span style='color:red'>{{ field.errors.as_text }}</span>
        </div>
      {% endfor %}

      <button class="btn btn-primary"> <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> Save </button>

    </form>
      </div>

  </div>
</div>


{% endblock %}

src/templates/jobs/detail_base.html
{% extends "base.html" %}


{% block body %}

<h2>Job {{ job.id }}</h2>
<hr>

<div class="row">
  <div class="col-lg-12">
    {% if job.status != job.PREPROCESSING %}
    <ul class="nav nav-tabs">
      {% if job.status == job.ADDED %}
      <li role="presentation" class="{% if view == 'configure1' %}active{% endif %}">
        <a href="{% url 'jobs:configure1' job.id %}">HemeLB Config</a>
      </li>
      <li role="presentation" class="{% if view == 'configure2' %}active{% endif %}">
        <a href="{% url 'jobs:configure2' job.id %}">Job config</a>
      </li>
      {% endif %}
      <li role="presentation" class="{% if view == 'overview' %}active{% endif %}">
      <a href="{% url 'jobs:overview' job.id %}">Overview</a>
      </li>

      {% if job.status != job.ADDED %}
      <li role="presentation" class="{% if view == 'detail' %}active{% endif %}">
        <a href="{% url 'jobs:details' job.id %}">Detail</a>
      </li>
      {% endif %}
    </ul>
    {% endif %}
  </div>
</div>

{% block body_detail %}
{% endblock %}



{% endblock %}

src/templates/jobs/details.html
{% extends "jobs/detail_base.html" %}
{% load hemeweb_tags %}

{% block body_detail %}



<h3>Job status: {{ job.get_status_display }} {% if job.status == 'DONE' and job.output_file == '' %} preparing output... {% endif %}</h3>
{% if job.output_file %}

<h3>Output file</h3>
<pre class="pre-scrollable" id="output">

  <a target="_blank" href="{{ job.output_file.url }}">{{ job.output_file.name }} ({{ job.output_file.size | humanize }})</a>

</pre>


  <h3>Simulation file URL</h3>

<pre class="pre-scrollable" id="url">
  {{ job.get_share_url }}

</pre>
{% endif %}

<h3>Stdout</h3>
<pre class="pre-scrollable" id="stdout">
{{ stdout|linebreaksbr }}
</pre>

<h3>Stderr</h3>
<pre class="pre-scrollable" id="stderr">
{{ stderr|linebreaksbr }}
</pre>

<h3>HemeLB output</h3>
<pre class="pre-scrollable" id="hemelb">
{{ hemelb|linebreaksbr }}
</pre>




{% endblock %}


{% block extra_javascript %}
<script type="text/javascript" >


  var objectId = "{{ object.id }}",
      $stdout = $('#stdout'),
      $stderr = $('#stderr'),
      $hemelb = $('#hemelb'),
      status = "{{ job.get_status_display }}";

  $stdout.scrollTop(999999999);
  $stderr.scrollTop(999999999);
  $hemelb.scrollTop(999999999);

  $(document).ready(function(){
    setInterval(function(){
      $.get('/' + objectId + '/output.json', function(data){
        $stdout.text(data.stdout).scrollTop(999999999);
        $stderr.text(data.stderr).scrollTop(999999999);
        $hemelb.text(data.hemelb).scrollTop(999999999);
        if (status != data.status) {
          location.reload();
        }
      });
    }, 10000);
  });
</script>
{% endblock %}

src/templates/jobs/index.html
{% extends "base.html" %}

{% block body %}

<div class="row">
  <div class="col-lg-6 col-lg-offset-3 ">
    <div class="panel panel-default center">
      <div class="panel-body">
        <p>Welcome to HemeWeb homepage! HemeWeb aim to allow users to run blood flow simulation using HemeLB from web browser. To create a new simulation job, please press the Add new
    job button. To view past simulation's overview please click on one of the Job IDs below.</p>
    </div>
      </div>
  </div>
</div>

<div class="row bottom-padding">
<div class="col-lg-2 col-lg-offset-10">
  <a href="{% url 'jobs:add' %}" class="btn btn-primary">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    Add new job
  </a>
</div>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
    <!-- Default panel contents -->
      <div class="panel-heading">HemeWeb Job Index</div>
    <table class="table table-striped">
      <thead>
        <tr>
          <td><strong>Job ID</strong></td>
          <td><strong>Submission time</strong></td>
          <td><strong>Status</strong></td>
        </tr>
      </thead>
      <tbody>
      {% for job in object_list %}
      <tr>
        <td>
          <a href="{{ job.get_next_step_url }}"> {{ job.id }} </a>
        </td>
        <td>
          {{ job.created }}
        </td>
        <td>
          {{ job.get_status_display }}
        </td>
      </tr>
      {% empty %}
        <tr><td colspan="3">No Jobs submitted</td></tr>
      {% endfor %}
      </tbody>
    </table>
    </div>

  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    {% if is_paginated %}
      <nav>
        <ul class="pagination">

          {% if page_obj.has_previous %}
          <li>
            <a href="?page={{ page_obj.prev_page }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
          {% endif %}

          <li><a>{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</a></li>

          {% if page_obj.has_next %}
          <li>
            <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>

    {% endif %}

  </div>
</div>

{% endblock %}

src/templates/jobs/new_add.html
{% extends "base.html" %}
{% load hemeweb_tags %}

{% block body_class %} job-add {% endblock %}

{% block body %}

<div class="row bottom-padding">
  <div class="col-lg-12">
    <div class="alert alert-info" role="alert">
    There are several ways of setting up a HemeLB flow simulation. Choose whether to create a new job from scratch or reuse an existing configuration
    </div>
  </div>
</div>

<div class="row">

<div class="col-lg-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title">Create new job from unprocessed inputs</h2>
    </div>
    <div class="panel-body">
        <form method="post" action="{% url 'jobs:setup' %}" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in preprocess_form.visible_fields %}
            <div class="form-group">

              <label for="{{ field.name }}">{{ field.label_tag }}</label>
              {{ field|addcss:"form-control" }}
              <span style='color:red'>{{ field.errors.as_text }}</span>
            </div>
          {% endfor %}
          <button class="btn btn-primary"> Submit </button>
        </form>
        <hr />

        <p>Use this form for unprocessed input files. HemeWeb will run a pre-processing script and allow you to configure the simulation after it is done.</p>
    </div>
  </div>
</div>




  <div class="col-lg-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">Create new job from preprocessed inputs</h2>
      </div>
      <div class="panel-body">
          <form method="post" action="{% url 'jobs:add' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in new_job_form.visible_fields %}
              <div class="form-group">

                <label for="{{ field.name }}">{{ field.label_tag }}</label>
                {{ field|addcss:"form-control" }}
                <span style='color:red'>{{ field.errors.as_text }}</span>
              </div>
            {% endfor %}
            <button class="btn btn-primary"> Submit </button>
          </form>
          <hr />
        <p>Use this form if your input files have been pre-processed. HemeWeb will read from the pre-processed files and allow you to configure the simulation.</p>
      </div>
    </div>
  </div>



  <div class="col-lg-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">Use previous HemeWeb job by ID</h2>
      </div>
      <div class="panel-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in previous_job_form.visible_fields %}
              <div class="form-group">

                <label for="{{ field.name }}">{{ field.label_tag }}</label>
                {{ field|addcss:"form-control" }}
                <span style='color:red'>{{ field.errors.as_text }}</span>
              </div>
            {% endfor %}
            <button class="btn btn-primary"> Submit </button>
          </form>
          <hr />
        <p>Create a new job from past HemeWeb's job configuration. Specify the ID of the job, and HemeWeb will take care of copying all configurations and inputs from that simulation</p>
      </div>
    </div>
  </div>

  <div class="col-lg-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">Use previous HemeWeb job by URL</h2>
      </div>
      <div class="panel-body">
          <form method="post" action="{% url 'jobs:add_from_url' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in url_form.visible_fields %}
              <div class="form-group">

                <label for="{{ field.name }}">{{ field.label_tag }}</label>
                {{ field|addcss:"form-control" }}
                <span style='color:red'>{{ field.errors.as_text }}</span>
              </div>
            {% endfor %}
            <button class="btn btn-primary"> Submit </button>
          </form>
          <hr />
        <p>Create a new job from past HemeWeb's job configuration. Specify the URL of the job, and HemeWeb will take care of copying all configurations and inputs from that simulation</p>
      </div>
    </div>
  </div>


</div>



{% endblock %}

src/templates/jobs/overview.html
{% extends "jobs/detail_base.html" %}
{% load hemeweb_tags %}

{% block body_class %}  Overview {% endblock %}

{% block body_detail %}


<div class="row">
  <div class="col-lg-12">
    <h2>Job Overview  {% if job.status == job.ADDED %} <small> We're almost done</h2> {% endif %}
  </div>
</div>


<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title">HemeLB config</h2>
      </div>
      <div class="panel-body">
        <p>
        GMY geometry file(.gmy): <a target="_blank" href="{{ job.input_file.url }}">{{ job.input_file.name }} ({{ job.input_file.size | humanize }})</a><br/><br/>
          HemeLB configuration file(.xml): {{ job.configuration_file.name }}
        </p>
        <div id="editor">{{ config_file }}</div>
      </div>
    </div>
  </div>
</div>



<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title">Job config</h2>
      </div>
      <div class="panel-body">
        <p>
          Machine type:  {{ job.get_instance_type_display }} <br/> <br/>
          How many machine: {{ job.instance_count }} <br/><br/>
          HemeLB version: <a target="_blank" href="{{ job.get_container_image_url }}">{{ job.get_container_image_display }}</a>
        </p>
      </div>
    </div>
  </div>
</div>


{% if job.status == job.ADDED %}
<div class="row">
  <div class="col-lg-12">
    <form method="post">
      {% csrf_token %}
      <input type="hidden" name="queue" id="queue" value="queue">
      <button class="btn btn-primary"> All good! Queue job </button>

    </form>
  </div>
</div>
{% endif %}


{% endblock %}


{% block extra_javascript %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/mode-xml.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/theme-solarized_dark.js"></script>


<script type="text/javascript" charset="utf-8">

  // Configure editor
  var editor = ace.edit("editor");
  editor.setTheme("ace/theme/solarized_dark");
  editor.getSession().setMode("ace/mode/xml");
  editor.getSession().setUseWrapMode(true);
  editor.setReadOnly(true);

</script>

{% endblock %}

src/templates/jobs/preprocessing.html
{% extends "jobs/detail_base.html" %}

{% block body_class %} configure_job_1 {% endblock %}

{% block body_detail %}


<div class="row">
  <div class="col-lg-12">
    <h2>Preprocessing profile and geometry files....</h2>
  </div>
</div>


{% endblock %}



{% block extra_javascript %}
<script type="text/javascript" charset="utf-8">
  // refresh the page in 15s
  setTimeout(function(){
      location.reload();
  }, 15000);
</script>

{% endblock %}